fix: fail decoding of reserved into null (#680)
This PR makes decoding of a value of type `reserved` into type `null`
always fail, consistently with the subtyping relation (`reserved` is not
a subtype of `null`).

So far,
```
$ didc encode '(variant { foo = null })' -t '(variant { foo : reserved })' | didc decode -t '(variant { foo : null })'
Error: input: 4449444c016b01868eb70270010000_
table: type table0 = variant { 5_097_222 : reserved }
wire_type: reserved, expect_type: null

Caused by:
    0: Fail to decode argument 0 from table0 to variant { foo }
    1: Subtyping error: unit_variant
```
fails, but
```
$ didc encode '(null)' -t '(reserved)' | didc decode -t '(null)'
(null : null)
$ didc encode '(record { foo = null })' -t '(record { foo : reserved })' | didc decode -t '(record { foo : null })'
(record { foo = null : null })
```
both succeed. This behavior is inconsistent and this PR makes all such
cases fail.

Additionally, the wire type of missing data is now set to `null`
(instead of `reserved`) so that it can be successfully decoded to `null`
as expected type.